name: Docker Publish
on:
  push:
    branches:
      - master
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build-push docker hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: sbegaudeau/spring-react-sample
          tags: latest
      - name: Build push Heroku		
        uses: docker/build-push-action@v1		
        with:		
          username: ${{ secrets.HEROKU_USERNAME }}		
          password: ${{ secrets.HEROKU_PASSWORD }}		
          registry: registry.heroku.com
          repository: spring-react-sample/web
          tags: latest
      - name: Build push Github Packages
        uses: docker/build-push-action@v1
        with:
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/server
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          tag_with_ref: true
          tags: latest